version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=spring-boot-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - networklocal

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kelsen.brito@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - networklocal

volumes:
  postgres_data:
  pgadmin_data:

networks:
  networklocal:
    driver: bridge
